### ISSUE TITLE
Player model and animation

### ISSUE THREAD

**Issue by Luchinho** [Naodo/HackAndSlashTemplate#2]
Dear Arnaud,

We would like to change the appearance and some of the animations of the main character but we can't. We can change the appearance of the BP Player but we can't give it the animations we want.  

Regards,

**Comment by Naodo** [comment]
Hello,

I'll need more informations on your problem before helping you.

What do you want to do with your animations ? Are they meant to be used for abilities or for movements (Idle / Walking / Running) ?

**Comment by Luchinho** [comment]
![image](https://user-images.githubusercontent.com/95274682/171406593-c1c46590-c4ac-4be4-a665-d05663b06886.png)
![image](https://user-images.githubusercontent.com/95274682/171407334-a9319f2f-fdfb-4652-809d-f7d0d2ea6656.png)
![image](https://user-images.githubusercontent.com/95274682/171407365-e2c2f680-9798-469d-b36d-a40365f8d69b.png)
So when I go into the BP_Player edit viewport, I can change the skeletal mesh with our new character. But then the "new character" has no animation. 
When I go to the asset details of the animations I can't change the skeleton, it's like blocked. So I don't know how to assign the animations to the new character.
Sorry it's hard to explain and I'm probably not very clear.

**Comment by Naodo** [comment]
Ok so the problem is that you cannot use the animations that are already in the template, they can only be used with the appropriate skeleton mesh (here paladin's one).

When your importing an animation, this window should pop up : 
 
![image](https://user-images.githubusercontent.com/78229567/171408524-c5015fc8-ce49-482b-ab5a-90f4ae17e547.png)

You should fill the skeleton field with the skeleton mesh of your character you created, then an animation sequence file should be created and you should be able to see your animation with your skeleton mesh.

Let me know if the problem is solved.

**Comment by Luchinho** [comment]
![image](https://user-images.githubusercontent.com/95274682/171410131-c0a5cebe-ea3e-4f50-a0f2-112510a0eee9.png)
I did as you said, when I run the animation in the asset details it works fine but when I run the game the player has no animation (it stays in T-pose).

**Comment by Naodo** [comment]
This is more of an Unreal problem you have here, check on the internet how to implement animations, there's great tutorial that will explain it better than I would do.
